FROM quay.io/konflux-ci/buildah-task:latest@sha256:ab0ba3b70f99faa74d2dd737422a965197af4922dec0109113bc535a94db0dfd

WORKDIR /scripts

COPY scripts/inject-icm.sh /scripts

LABEL \
  description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  io.k8s.description="Inject an ICM (image content manifest) file with content sets for backwards compatibility." \
  summary="Inject an ICM (image content manifest) file" \
  io.k8s.display-name="Inject an ICM (image content manifest) file" \
  name="Inject an ICM (image content manifest) file" \
  com.redhat.component="inject-icm"

ENTRYPOINT ["/scripts/inject-icm.sh"]

