apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/konflux-ci/build-tasks-dockerfiles?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "sbom-utility-scripts/***".pathChanged() || ".tekton/sbom-utility-scripts-push.yaml".pathChanged()
      || ".tekton/build-pipeline.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: build-tasks-dockerfiles
    appstudio.openshift.io/component: sbom-utility-scripts
    pipelines.appstudio.openshift.io/type: build
  name: sbom-utility-scripts-on-push
  namespace: rhtap-build-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rhtap-build-tenant/sbom-utility-scripts:{{revision}}
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: sbom-utility-scripts
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: '[{"type": "pip", "path": "sbom-utility-scripts/scripts/add-image-reference-script"},
      {"type": "pip", "path": "sbom-utility-scripts/scripts/base-images-sbom-script/app"},
      {"type": "pip", "path": "sbom-utility-scripts/scripts/index-image-sbom-script"},
      {"type": "pip", "path": "sbom-utility-scripts/scripts/merge-sboms-script"},
      {"type": "pip", "path": "sbom-utility-scripts/scripts/sbom-for-modelcar-task"},
      {"type": "pip", "path": "sbom-utility-scripts/scripts/sbom-for-oci-copy-task"}]'
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-sbom-utility-scripts
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
